name: Deploy to GitHub Pages 

on:
  workflow_dispatch
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        run: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: fetch secrets
        run: |
          echo "API=${{ secrets.REACT_APP_FB_API }}" > .env
          echo "MESSAGINGSENDERID=${{ secrets.REACT_APP_FB_MESSAGINGSENDERID }}" > .env
          echo "APPID=${{ secrets.REACT_APP_FB_APPID }}" > .env
          echo "MEASUREMENTID=${{ secrets.REACT_APP_FB_MEASUREMENTID }}" > .env

      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy